
/**
 * Write a description of class Problem12_HighlyDivisibleTriangularNumber here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 * 

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

 */
public class Problem12_HighlyDivisibleTriangularNumber
{
    public static void main(String args[]){
        long number = 0;
        long total = 0;
        int totalFactors = 2;
        while(totalFactors < 500){
        	total = number + total;
        	totalFactors = 2;//1 for 1, and 1 for total
        	//taking some of the stress off
        	if(total > 100000){
        	for(int i=2; i<total/2+1; i++){
        		boolean factor = isFactor(i, total);
        		if(factor)	
        			totalFactors++;
        	}
        	}
        	//System.out.println("Triangle number: " + total + " Number of Factors: " + totalFactors);
        	number++;
        }
        System.out.println("number: " + total + "total factors: " + totalFactors);
    }
    public static boolean isFactor(int possibleFactor, long number){
        if(number>0 && number%possibleFactor == 0){
        	return true;
        }
        return false;
        
    }

}
